#!/bin/sh

# Synchronizes calcurse with a CalDAV server

histsize=1000
data_dir="${XDG_DATA_HOME:-$HOME/.local/share}/calcurse"
logfile="$data_dir/caldav/log"

mkdir -p "$data_dir/caldav"
touch "$logfile"

# Do not do anything when synchronizing with a CalDAV server.
if [ -f "$data_dir/caldav/lock" ] ; then 
  if [ `stat --format=%Y "$data_dir/caldav/lock"` -le $(( `date +%s` - 1800 )) ]; then 
    rm "$data_dir/caldav/lock"
  else
    exit 1
  fi
fi

# Run the CalDAV synchronization script in the background.
if [ -d "$data_dir/caldav" ] && command -v calcurse-caldav >/dev/null; then
	(
		date="$(date +'%b %d %H:%M:%S')"
		echo "$date Running calcurse-caldav..."
		calcurse-caldav
		echo
	) >>$logfile 2>&1
fi

# keep the logfile short
tmp="$(mktemp)"
tail -$histsize "$logfile" > "$tmp"
cp "$tmp" "$logfile"
rm "$tmp"
