#! /usr/bin/env bash

# Usage 'gitsyncer [directory where the local git repo will be or is located] [repo to sync]'

root=$1
repo=$2
pkg_name="`echo ${repo##*/} | cut -d'.' -f1`"

mkdir -p "$root"
cd "$root"

if [ -d "$pkg_name" ] ; then
  cd $pkg_name
  git add .
  git commit -m "$(cat /etc/hostname)"
  git pull
  git push
else
  git clone $repo
fi
