#!/usr/bin/env bash

# [l]ast [w]orking [d]irectory

function fzf_lwd_file(){
  cat $last_wd_file | fzf --tac --no-sort
}

histsize=5000

[ $# -gt 0 ] || exit 1
touch "$last_wd_file"
case "$1" in 
  save)
    if [ -z "$2" ] ; then
      wd="$(pwd)"
    else
      wd="$2"
    fi

    grep $last_wd_file -e "^$wd\$" &> /dev/null && sed -i "\#^$wd\$#d" $last_wd_file 
    echo "$wd" >> $last_wd_file

    tail -$histsize "$last_wd_file" > "$last_wd_file.aux"
    cp "$last_wd_file.aux" "$last_wd_file"
    ;;
  print)
      tail "$last_wd_file" -n 1
    ;;
  load)
      last_wd="$(tail "$last_wd_file" -n 1)"
      [ -z "$last_wd" ] || cd "$last_wd"
    ;;
  history)
      fzf_lwd_file
    ;;
  history_cd)
      cdto="$(fzf_lwd_file)"
      [ -z "$cdto" ] || cd "$cdto"
    ;;
  *)
    echo "$1 unknown command" 1>2
    ;;
esac

