#!/bin/sh
# Give a battery name (Check the battery name from sys/class/power_supply/ e.g. BAT0 or BAT1 and pass it as an argument.
[ ! -e /sys/class/power_supply/BAT? ] && exit 1

case $BLOCK_BUTTON in
    3) pgrep -x dunst >/dev/null && notify-send "🔋 Battery module" "🔋: discharging
🛑: not charging
♻: stagnant charge
🔌: charging
⚡: charged
❗: battery very low!
- Text color reflects charge left" ;;
    *) [ -z $BLOCK_BUTTON ] || exit 0 ;;
esac

for battery in /sys/class/power_supply/BAT? ; do
capacity=$(cat "$battery"/capacity) || exit
status=$(cat "$battery"/status)

warn=" "

if ! [ "$status" = "Charging" ] &&  [ "$capacity" -le 15 ] ; then
  if [ "$capacity" -le 5 ] ; then
    notify-send "Battery almost empty!" --urgency=critical --app-name=silent
    paplay /usr/share/sounds/freedesktop/stereo/suspend-error.oga
  elif [ "$capacity" -le 10 ] ; then
    notify-send "Battery very low" --urgency=critical 
  else
    notify-send "Battery low " --urgency=critical --app-name=silent
    paplay /usr/share/sounds/freedesktop/stereo/dialog-warning.oga
  fi
fi

printf "%s%s%s\n" "$(echo "$status" | sed "s/,//;s/Discharging/🔋/;s/Not charging/🛑/;s/Charging/🔌/;s/Unknown/♻️/;s/Full/⚡/;s/ 0*/ /g;s/ :/ /g")" "$warn" "$(echo "$capacity" | sed -e 's/$/%/')"
done

