#!/bin/sh

case $BLOCK_BUTTON in
  1) #rund $TERMINAL -c st-256color-c -e $SHELL -c calcurse ;;
     rund "yad --calendar --no-buttons " ;;
  3) rund "st -c st-256color-ur -e $SHELL -c $STATUSBAR_AUX_BIN/timer" ;;
  *) [ -z $BLOCK_BUTTON ] || exit
esac

echo "`date '+%H:%M - %d/%m'` | "
