#!/bin/sh

cache_file="$HOME/.cache/coronavirus"

update_cache() { ping -q -c 1 1.1.1.1 >/dev/null || exit 1
#    while : ; do 
#	  ping -q -c 1 1.1.1.1 &>/dev/null && break
#	  sleep 3 
#   done 
	curl -sf "https://corona-stats.online/" > ${cache_file} 
}

display() {
    uruguay=`grep -F Uruguay ${cache_file}  | sed  's/\x1b\[[0-9;]*m//g' | sed "s/\s*//g ; s/│/;/g ; s/║//g" | awk -F';' '{print " 😷"$8 " 🏥" ($9!="" ? $9 : 0) " 💀" ($5!="" ? $5 : 0)}'`
    # " (" ($4!="" ? $4 : 0) " )" 
    # "😀" $7 
    echo $uruguay
}

if [ ! -f ${cache_file} ] || [ "$(stat -c %y ${cache_file} | awk '{print $1}')" != "$(date '+%Y-%m-%d')" ] ; then
    update_cache 
fi

case $BLOCK_BUTTON in
    2) update_cache && display ;;
    *) ([ -z $BLOCK_BUTTON ] && display) || exit 1 ;;
esac

