#!/bin/sh

# Status bar module for disk space
# $1 should be drive mountpoint
# $2 is optional icon, otherwise mountpoint will displayed

[ -z "$1" ] && exit

icon="$2"
[ -z "$2" ] && icon="💽"

case $BLOCK_BUTTON in
	1) rund $TERMINAL -c st-256color-c $SHELL -c "cd  ; ncdu" ;;
	3) rund $TERMINAL -c st-256color-c $SHELL -c "removable-pkgs" ;;
	2) pgrep -x dunst >/dev/null && notify-send "💽 Disk space" "$(df -h --output=target,used,size)" ;;
  *) [ -z $BLOCK_BUTTON ] || exit 1 ;;
esac

printf "%s %s\n" "HDD:" "$(df -h "$1" | awk ' /[0-9]/ {print $3 "/" $2}')"
