#!/bin/sh

case $BLOCK_BUTTON in
  1) "rund st -c st-256color-c $SHELL -c "btop"" ;;
	3) notify-send "🧠 Memory hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
esac

echo "RAM: `free -h | awk '/^Mem:/ {print $3 "/" $2}'`"
