#!/bin/sh

# i3blocks newsboat module.
# Displays number of unread news items and an loading icon if updating.
# When clicked, brings up `newsboat`.

[ $WM = "bspwm" ] && BLOCK_BUTTON=$1

case $BLOCK_BUTTON in
        1)  pkill newsboat &>/dev/null
            "$TERMINAL" -e newsboat &>/dev/null  
            ;;
        3) "$TERMINAL" -e nvim .config/newsboat/urls &>/dev/null  ;;
        *) [ -z $BLOCK_BUTTON ] || exit 0 ;;
esac

#if [ ! $BLOCK_BUTTON -eq 0 ] && [ $WM = "bspwm" ] ; then
	# polybar-msg hook news 1 &>/dev/null 
	# exit
# fi

while : ; do 
	newsboat -x reload &>/dev/null
  [ $? -eq 1 ] || break
 	sleep 10 &>/dev/null
 done

echo "$(newsboat -x print-unread | awk '{ print "📰 " $1}' | sed s/^0$//g)$(cat ~/.config/newsboat/.update 2>/dev/null)"
