#!/bin/sh

[ $WM = "bspwm" ] && BLOCK_BUTTON=$1

case $BLOCK_BUTTON in
	1) rund st -c st-256color-ur -e upgrade &> /dev/null ;;
  *) [ -z $BLOCK_BUTTON ] || exit 0 ;;
esac

updates=`checkupdates`

pack_num=`echo "$updates" | sed "/^$/d" | grep -v "\[ignored\]" | wc -l | sed "s/^//;s/^0$//g"`

if [ -z "$pack_num" ]; then
	echo "📦 0"
else
	echo "📦 $pack_num"
fi
