#!/usr/bin/env bash

[ $WM = "bspwm" ] && BLOCK_BUTTON=$1

case $BLOCK_BUTTON in
	1) $TERMINAL -e tmux new \"$TMUX_BIN/open_and_kill_session\" &> /dev/null ;;
	3) $TERMINAL -e tmux new \"$TMUX_BIN/open_and_kill_session_detached\" &> /dev/null ;;
  *) [ -z $BLOCK_BUTTON ] || exit 0 ;;
esac

total=`tmux list-sessions -F '#{session_attached} #{session_activity} #{session_id}'`
detached=` echo "$total" | awk '/^0/{print $2,$3}' | wc -l`



echo "tmux `echo "$total" | wc -l` ($detached)"
