#!/bin/sh
SINK=`pacmd list-sinks | grep "*" | awk '{ print $3 }'`

volstat=`pactl list sinks | grep '^[[:space:]]Volume:' | \
    head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'`

case $BLOCK_BUTTON in
	1) rund pavucontrol-qt --tab 5 ;;
	4) 	if [ "$volstat" -lt "200" ]; then
	    	pactl set-sink-volume @DEFAULT_SINK@ +5% 
	  	fi
		;;
	5) pactl set-sink-volume @DEFAULT_SINK@ -5% ;;
esac

volstat=`pactl list sinks | grep '^[[:space:]]Volume:' | \
    head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'`
	
if [ "$volstat" -gt "70" ]; then
	icon="🔊"
elif [ "$volstat" -gt "30" ]; then
	icon="🔉"
elif [ "$volstat" -gt "0" ]; then
	icon="🔈"
else
	icon="🔇"
fi

printf "%s %s%%\\n" "$icon" "$volstat"
