#!/bin/sh
cache_file1="$HOME/.cache/weatherreport1"
cache_file2="$HOME/.cache/weatherreport2"

getforecast() { ping -q -c 1 1.1.1.1 >/dev/null || exit 1
#	while : ; do 
#		ping -q -c 1 1.1.1.1 &>/dev/null && break
#		sleep 3 
#	done
    curl -sf "https://www.inumet.gub.uy/" > ${cache_file1}
    curl -sf "http://wttr.in/montevideo" > ${cache_file2}
}

showweather() {
    min=`cat ${cache_file1} | grep pron_min_0  | cut -d">" -f2 | cut -d"<" -f1`
    max=`cat ${cache_file1}| grep pron_max_0  | cut -d">" -f2 | cut -d"<" -f1`
    current=`sed 's/\x1b\[[0-9;]*m//g' ${cache_file2} | grep °C  | head -1| awk '{print $(NF-1)}' | cut -d"." -f1`
    echo "🌡$curren° 🧊$min° 🌞$max°"
}

[ -f ${cache_file1} ] || [ -f ${cache_file2} ] || getforecast 

if [ "$(stat -c %y ${cache_file1} | awk '{print $1}')" != "$(date '+%Y-%m-%d')" ] ; then 
    getforecast
fi

showweather

case $BLOCK_BUTTON in
    3) showweather;;   
    2) getforecast && showweather ;;
esac
