#!/bin/sh

case $BLOCK_BUTTON in
  1) rund "st -c st-256color-c $SHELL -c "htop"" ;;
  3) notify-send "🖥 CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)" ;;
  *) [ -z $BLOCK_BUTTON ] || exit 0 ;;
esac

#sensors | awk '/Core 0/ {print $3}'
echo "| CPU: `top -b -n1 | grep "Cpu(s)" | awk '{print $2 + $4}'` %"
