#!/usr/bin/env bash

shopt -s nullglob globstar

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | grep "^otp-.*" | sed 's#^otp-##g' | dmenu "$@")

[[ -n $password ]] || exit

# pass show -c "$password" 2>/dev/null (copy to clipboard?)
pass otp "otp-$password" | { IFS= read -r pass; printf %s "$pass"; } |
  xdotool type --clearmodifiers --file -
xdotool key --clearmodifiers KP_Enter 
