#!/usr/bin/env bash

# [l]ast [w]orking [d]irectory (or file TODO change name)

function fzf_lwd_file(){
  cat $last_wd_file | fzf --tac --tiebreak="length,end" --preview-window=right:25%
}

histsize=5000

[ $# -gt 0 ] || exit 1
touch "$last_wd_file"
case "$1" in 
  save)
    wd=${2:-"$(pwd)"}

    sed -i "\#^$wd\$#d" $last_wd_file 

    echo "$wd" >> $last_wd_file

    tail -$histsize "$last_wd_file" > "$last_wd_file.tmp"
    cp "$last_wd_file.tmp" "$last_wd_file"
    rm "$last_wd_file.tmp"
    ;;
  clean)
    while IFS="" read -r p || [ -n "$p" ] ; do
      if [ -e "$p" ] ; then 
        echo "$p"  >> "$last_wd_file.tmp"
      else
        echo "$p does not exist"
      fi
    done < $last_wd_file
    cp "$last_wd_file.tmp" "$last_wd_file"
    rm "$last_wd_file.tmp"

    ;;

  print)
      tail "$last_wd_file" -n 1
    ;;
  load)
      last_wd="$(tail "$last_wd_file" -n 1)"
      if [ -e "$last_wd" ] ; then
        if [ -d $last_wd ] ; then 
          cd "$last_wd"
        else
          cd "${last_wd%/*}"
        fi
      fi
    ;;
  history)
      fzf_lwd_file
    ;;
  history_cd)
      sel="$(fzf_lwd_file)"
      if [ -e "$sel" ] ; then
        if [ -d $sel ] ; then 
          cd "$sel"
        else
          open "$sel"
          cd "${sel%/*}"
        fi
      fi
    ;;
  *)
    echo "$1 unknown command" 1>2
    ;;
esac
