#!/usr/bin/env bash

# [l]ast [w]orking [f]ile

function fzf_lwd_file(){
  cat $last_wf_file | fzf --tac --tiebreak="length,end" --preview-window=right:25%
}

histsize=5000

[ $# -gt 0 ] || exit 1
touch "$last_wf_file"
case "$1" in 
  save)
    wf=${2:-"$(pwd)"}

    sed -i "\#^$wf\$#d" $last_wf_file 

    echo "$wf" >> $last_wf_file

    tail -$histsize "$last_wf_file" > "$last_wf_file.tmp"
    cp "$last_wf_file.tmp" "$last_wf_file"
    rm "$last_wf_file.tmp"
    ;;
  clean)
    while IFS="" read -r p || [ -n "$p" ] ; do
      if [ -e "$p" ] ; then 
        echo "$p"  >> "$last_wf_file.tmp"
      else
        echo "$p does not exist"
      fi
    done < $last_wf_file
    cp "$last_wf_file.tmp" "$last_wf_file"
    rm "$last_wf_file.tmp"

    ;;

  print)
      tail "$last_wf_file" -n 1
    ;;
  load)
      last_wd="$(tail "$last_wf_file" -n 1)"
      [ -z "$last_wd" ] || cd "$last_wd"
    ;;
  history)
      fzf_lwd_file
    ;;
  history_cd)
      cdto="$(fzf_lwd_file)"
      [ -z "$cdto" ] || cd "$cdto"
    ;;
  *)
    echo "$1 unknown command" 1>2
    ;;
esac

