#!/usr/bin/env bash
set -o xtrace       # Trace the execution of the script (debug)

output_dir="../vimwiki_html"
tmp_dir="/tmp/mds2htmls"

mkdir -p $output_dir
mkdir -p 
for file in $(find '.' -name '*.md' -type f | xargs -I '{}' basename '{}' .md) ; do
  sed -r 's/(.*)\.md/\1.html/g' "$file.md" > "$tmp_dir/$file.md"
  pandoc "$tmp_dir/$file.md" -t html -o "$output_dir/$file.html"
done
find '.' ! -name '*.md' -type f | xargs -I '{}' cp '{}' $output_dir/'{}'
