#!/usr/bin/env bash

sel="$(realpath $@)"

# open
if [ -d "$sel" ] ; then
  cd $sel
elif [ -e "$sel" ] ; then
  # save opened file
  lwd save "$sel"

  # cd to the folder containing file
  dir=${sel%/*}
  [ -d $dir ] && cd ${sel%/*}

  # open the file int the editor
  exe-and-set-title $EDITOR $sel
fi

# reset title
set_terminal_title
