#!/usr/bin/env bash

cd "$ROS2WS"
rosdep install -i --from-path src --rosdistro foxy -y
colcon build --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
# colcon build --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=1

