#!/bin/bash
clean_kernels(){
  sudo apt-mark auto '^linux-image-*' &>/dev/null
  sudo apt-mark auto '^linux-headers-*' &>/dev/null
  sudo apt autoremove -y
}

clean_apt_cache(){
  sudo apt-get clean
}

clean_snap(){
set -eu
snap list --all | awk '/disabled/{print $1, $3}' |
    while read snapname revision; do
        snap remove "$snapname" --revision="$revision"
    done
}

while test $# -gt 0; do
  case "$1" in
    -h|--help)
      echo "myapt [options] command"
      echo " "
      echo "options:"
      echo "  -h, --help                show brief help"
      echo "  -d, --debug               enable debug info"
      echo " "
      echo "commands: "
      echo "  all                       executes all commands"
      echo "  kernel                    cleans obsolete headers and modules"
      exit 0
      ;;
    -d|--debug)
      shift
      set -o xtrace
      ;;
    kernels)
      shift
      clean_kernels
      ;;  
    apt_cache)
      shift
      clean_apt_cache
      ;;  
    snap)
      shift
      clean_snap
      ;;  
    all)
      shift
      clean_kernels
      clean_apt_cache
      exit 0
      ;;
    *)
      echo "ERROR: \"$1\" option or command unknown"
      exit 1
      ;;
  esac
done



