#!/bin/bash

case $1 in
0) 
    xrandr --output DVI-I-0 --right-of HDMI-0 --auto
    pkill barrier*
    ;;
1) 
    xrandr --output DVI-I-0 --off
    pkill barrier*
    rund barrier
    ;;
*)
    echo "0 - pc"
    echo "1 - pc+laptop"
    ;;
esac



