#!/bin/sh

# Usage: exe-and-set-title [COMMAND]
#
# Executes the COMMAND and sets the terminal title (and tmux window title if using tmux) 
# to a simplified form of the executed command

fullcmd=`echo "$@" | sed "s#-- ##g" | sed "s#$HOME#~#g"`
exe=`echo $fullcmd | sed 's/ .*//' | sed 's#.*/##' `
args=`echo $fullcmd | sed 's/.* //'`
echo -en "\e]2;$exe $args\a"
[ -z $TMUX ] || echo -ne "\033k$exe $args\033\\"
$@
