#!/bin/bash
debug=0
myapt_folder=$HOME/bin/.myapt
cmd=null
target=null
while test $# -gt 0; do
  case "$1" in
    -h|--help)
      echo "myapt [options] command"
      echo " "
      echo "options:"
      echo "  -h, --help                show brief help"
      echo "  -d, --debug               enable debug info"
      echo " "
      echo "commands: "
      echo "  install [package]"
      echo "  remove  [package]"
      exit 0
      ;;
    -d|--debug)
      shift
      debug=1
      ;;
    install|remove)
      cmd=$1
      shift
      target=$1
      break
      ;;
    *)
      echo "ERROR: \"$1\" option or command unknown"
      exit 1
      ;;
  esac
done

if [ $debug -eq 1 ]; then
  set -o xtrace
fi

if [ ! -d "$myapt_folder" ] ; then
  echo "ERROR: \"$myapt_folder\" does not exist"
  exit 1
fi

if [ $cmd = null ] ; then
  echo "ERROR: no command"
  exit 1
fi

if [ ! -e "$myapt_folder/$target" ] ; then
  echo "ERROR: \"$myapt_folder/$target\" does not exist"
  exit 1
fi

sh "$myapt_folder/$target" -d "$debug" "$cmd"

