#!/bin/bash
lastVer=`curl -s https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases/latest | rev |cut -f 4 -d '/' |rev| cut -d '"' -f 1`
if [ ! -f /tmp/$lastVer-linux-x64.zip ] ; then
    wget -P /tmp/ https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases/download/$lastVer/$lastVer-linux-x64.zip
    
fi
if [ -f /tmp/libffmpeg.so ] ; then
    rm /tmp/libffmpeg.so
fi
unzip -o /tmp/$lastVer-linux-x64.zip -d /tmp/
if [ -d /usr/lib/x86_64-linux-gnu/opera/lib_extra ] ; then
    rm -R /usr/lib/x86_64-linux-gnu/opera/lib_extra
fi
mkdir /usr/lib/x86_64-linux-gnu/opera/lib_extra
mv /tmp/libffmpeg.so /usr/lib/x86_64-linux-gnu/opera/lib_extra


