#!/bin/bash
if [ ! -z $2 ] ; then
  echo "Wrong syntax: playNes $@"
  echo "Try: playNes [rom]"
	exit 1
fi
if [ -f "$HOME/Games/nes/$1" ] ; then
  height=`xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*[0-9]+x([0-9]+).*$/\1/'`
  width=`echo $height*1.143 | bc | cut -d . -f 1`
  fceux --loadstate 0 --savestate 0 --fullscreen 1  --xres $width --yres $height "$HOME/Games/nes/$1"
else
  echo "No existe ese rom"
fi
