#!/usr/bin/env bash

export TERM="st-256color"
if [ -z $last_wd_file ] ; then
  ranger --choosedir=$last_wd_file
else
  cd "`cat $last_wd_file`"
  ranger --choosedir=$last_wd_file
fi
[ -z $last_wd_file ] || cd "`cat $last_wd_file`"
$SHELL
