#!/bin/bash

case $1 in
0) # default
    xgamma -quiet -rgamma 1 -ggamma 1 -bgamma 1
    pkill redshift
    ;;
1) # laptop
    xgamma -quiet -rgamma 1 -ggamma 0.95 -bgamma 1.20
    pkill redshift
    $HOME/bin/rund redshift-gtk -t 7000:7000 -r -l 0:0
    ;;
2) # monitor
    xgamma -quiet -rgamma 0.85 -ggamma 0.85 -bgamma 0.85
    pkill redshift
    ;;
3) # romi-10000k
    xgamma -quiet -rgamma 0.77 -ggamma 0.85 -bgamma 1.0
    pkill redshift
    ;;
4) # romi-10000k mas brillo
    xgamma -quiet -rgamma 0.93 -ggamma 1 -bgamma 1.14
    pkill redshift
    ;;
5) # monitor v2
    xgamma -quiet -rgamma 0.95 -ggamma 0.95 -bgamma 1.15
    pkill redshift
    $HOME/bin/rund redshift-gtk -t 7500:7500 -r -l 0:0
    ;;
*)
    echo "1 - laptop"
    echo "2 - monitor"
    ;;
esac
