#! /bin/bash

bspc subscribe node_flag | 
    while read -r line; do
		flag=$(echo "$line" | cut -d' ' -f5)
		if [ "$flag" = "hidden" ]  ; then
			value=$(echo "$line" | cut -d' ' -f6)
			if [ "$value" = "on" ] ; then
				echo "HOLA"
				ws=$(echo "$line" | cut -d' ' -f2)
				node=$(echo "$line" | cut -d' ' -f3)
				bspc node $node -g hidden=off
				bspc node $node -d M
				bspc node $node -g hidden=on
				#bspc desktop $ws -f
			fi
		fi
	done
