#!/bin/env bash
nodes=( $(bspc query -N -n .hidden.window))
line=""
for node in ${nodes[@]} ; do
	line=${line}`ps -e | grep $(xdotool getwindowpid $node) | grep -v grep | awk '{print $4}'`" : "`xtitle $node`'\n'
done

s=$(printf "$line" | rofi -dmenu -i -format i -p "Hidden windows")
[[ -n "$s" ]] && bspc node "${nodes[$s]}" -d focused -g hidden=off -g sticky=off -f

#[[ -n "$s" ]] && bspc node "${nodes[$s]}" -n focused -g hidden=off -f
