#!/bin/bash
debug=0
scriptsFolder="$HOME/.myapt"
cmd=null
while test $# -gt 0; do
  case "$1" in
    -h|--help)
      echo "Usage: apt [options] command"
      echo " "
      echo "options:"
      echo "-h, --help                show brief help"
      echo "-d, --debug               enable debug info"
      exit 0
      ;;
    -d|--debug)
      shift
      debug=$1
      shift
      ;;
    install|remove)
      cmd=$1
      break
      ;;
    *)
      echo "ERROR: \"$1\" option or command unknown"
      exit 1
      ;;
  esac
done

if [ $debug -eq 1 ]; then
  set -o xtrace
fi

case "$cmd" in
  install)
    #get latest
    cd /tmp
    rm -R -f grive2/ 2>/dev/null
    git clone https://github.com/vitalif/grive2
    cd grive2
    sudo apt-get install git cmake build-essential libgcrypt11-dev libyajl-dev libboost-all-dev libcurl4-openssl-dev libexpat1-dev libcppunit-dev binutils-dev pkg-config zlib1g-dev
    mkdir build
    cd build
    cmake ..
    make -j4
    sudo make install

    cd /tmp
    rm -R -f grive2/ 2>/dev/null

    exit 0 
    ;;
  remove)
    sudo rm /usr/local/lib/systemd/user/grive-changes@.service
    sudo rm /usr/local/lib/systemd/user/grive-timer@.service
    sudo rm /usr/local/lib/systemd/user/grive-timer@.timer
    sudo rm /usr/local/lib/grive/grive-sync.sh
    sudo rm /usr/local/bin/grive
    sudo rm /usr/local/share/man/man1/grive.1
    ;;
  *)
    echo "ERROR: \"$cmd\" option or command unknown"
    exit 1
    ;;
esac
