#! /bin/bash

bspc subscribe node_add node_remove | 
    while read -r line; do
		var=$(echo $line | awk '{print $1}')
		echo $var
		#if [ "$var" == "node_add" ] && [ "`bspc query -N -n .!focused.local.tiled.leaf | wc -w`" -gt "1" ]; then
		bspc node -n biggest.local
		bspc node -s biggest.local
		#fi
		#bspc node -s biggest.local.tiled.leaf
    done;

