#!/bin/sh

# A dmenu binary prompt script.
# Gives a dmenu prompt labeled with $1 to perform command $2.
# For example:
# `./prompt "Do you want to shutdown?" "shutdown -h now"`

#[ "$(printf "No\\nYes" | dmenu -i -p "$1" -nb "#1f1f1f" -sb "#353535" -sf white -nf gray )" = "Yes" ] && $2
selected="$(printf "🔒\tLock\\n⏻ \tShutdown\\n↩ \tLogout\\n⟳ \tRestart\\n⏾\tSuspend\\n🐻\tHibernate" | rofi -dmenu -i -p "Leave" -nb "#1f1f1f" -sb "#353535" -sf white -nf gray )"

action=$(echo "$selected" | cut -d"	" -f2)

case $action in
	Shutdown) shutdown -h now ;;
  Logout) kill -9 -1 ;; 
  Restart) systemctl reboot -i ;;
	Suspend) systemctl suspend ;;
	Lock) xscreensaver-command -lock ;;
	Hibernate) systemctl hibernate ;;
esac
