#!/bin/sh

# The famous "get a menu of emojis to copy" script.

# Must have xclip installed to even show menu.
# xclip -h 2>/dev/null || exit 1

chosen=$(cut -d ';' -f1 $MY_BIN/dmenu/.dmenu_unicode/emoji | dmenu -p unicode -i -l 15 | sed "s/ .*//")

[ "$chosen" != "" ] || exit

xdotool type --delay 100 "$chosen"

# echo "$chosen" | tr -d '\n' | xclip -selection clipboard
