#!/bin/sh

# The famous "get a menu of emojis to copy" script.

# Must have xclip installed to even show menu.
xclip -h 2>/dev/null || exit 1

chosen=$(cut -d ';' -f1 $HOME/bin/.dmenu_unicode/emoji | dmenu -i -l 20 | sed "s/ .*//")

[ "$chosen" != "" ] || exit

xdotool type --delay 100 "$chosen"

echo "$chosen" | tr -d '\n' | xclip -selection clipboard
