#!/bin/bash

# based on: https://github.com/davatorium/rofi-scripts/blob/master/monitor_layout.sh

XRANDR=$(which xrandr)

MONITORS=( $( ${XRANDR} | awk '( $2 == "connected" ){ print $1 }' ) )
DISCONECTED_MONITORS=( $( ${XRANDR} | awk '( $2 == "disconnected" ){ print $1 }' ) )

NUM_MONITORS=${#MONITORS[@]}
NUM_DISCONECTED_MONITORS=${#DISCONECTED_MONITORS[@]}

TITLES=()
COMMANDS=()


function gen_xrandr_only()
{
    selected=$1
    cmd="xrandr"
    for entry in $(seq 0 $((${NUM_MONITORS}-1))) ; do
        if [ $MONITORS[$selected] != $MONITORS[$entry] ] ; then
            cmd="$cmd --output ${MONITORS[$entry]} --off"
        fi
    done
    for entry in $(seq 0 $((${NUM_DISCONECTED_MONITORS}-1))) ; do
        cmd="$cmd --output ${DISCONECTED_MONITORS[$entry]} --off"
    done

    cmd="$cmd --output ${MONITORS[$selected]} --auto "

    echo $cmd
}

declare -i index=0

for entry in $(seq 0 $((${NUM_MONITORS}-1))) ; do
    # TILES[$index]="Only ${MONITORS[$entry]}"
    TILES[$index]="${MONITORS[$entry]}"
    COMMANDS[$index]=$(gen_xrandr_only $entry)
    index+=1
done

##
# Dual screen options
##
for entry_a in $(seq 0 $((${NUM_MONITORS}-1))) ; do
    for entry_b in $(seq 0 $((${NUM_MONITORS}-1))) ; do
        if [ $entry_a != $entry_b ] ; then
            # TILES[$index]="Dual Screen ${MONITORS[$entry_a]} | ${MONITORS[$entry_b]}"
            TILES[$index]="${MONITORS[$entry_a]} left of ${MONITORS[$entry_b]}"
            COMMANDS[$index]="xrandr --output ${MONITORS[$entry_b]} --auto \
                              --output ${MONITORS[$entry_a]} --auto --left-of ${MONITORS[$entry_b]}"

            index+=1

            # TILES[$index]="Dual Screen ${MONITORS[$entry_a]} | ${MONITORS[$entry_b]}"
            TILES[$index]="${MONITORS[$entry_a]} above ${MONITORS[$entry_b]}"
            COMMANDS[$index]="xrandr --output ${MONITORS[$entry_b]} --auto \
                              --output ${MONITORS[$entry_a]} --auto --above ${MONITORS[$entry_b]}"

            index+=1

            # TILES[$index]="Clone Screen ${MONITORS[$entry_a]} := ${MONITORS[$entry_b]}"
            TILES[$index]="${MONITORS[$entry_a]} same as ${MONITORS[$entry_b]}"
            COMMANDS[$index]="xrandr --output ${MONITORS[$entry_a]} --auto \
                              --output ${MONITORS[$entry_b]} --auto --same-as ${MONITORS[$entry_a]}"

            index+=1
        fi
    done
done


##
#  Generate entries, where first is key.
##
function gen_entries()
{
    for a in $(seq 0 $(( ${#TILES[@]} -1 ))) ; do
        echo $a ${TILES[a]}
    done
}

config-keyboard # In the event that a change in the monitor layout implies a change in the keyboards 

# Call menu
SEL=$( gen_entries | rofi -dmenu -i -p "Monitor Setup" | awk '{print $1}' )

[ -z $SEL ] && exit $?

# Call xrandr
$( ${COMMANDS[$SEL]} )
# echo ${COMMANDS[$SEL]}

# reset wallpaper
nitrogen --set-scaled $WALLPAPER_FILE &> /dev/null & 
