#! /bin/bash

bspc subscribe node_add node_remove node_activate node_state | 
    while read -r line; do
		echo "$line"
		var=$(echo $line | awk '{print $1}')
		id=$(echo "$line" | awk '{print $5}')
		
		if [ -z `bspc query -T -n $id | grep '"state":"floating"'` ] ; then
			if [ "$var" = "node_add" ] ; then
				$BSPWM_BIN/mode/stack $id 1> /dev/null
			else
				$BSPWM_BIN/mode/stack 1> /dev/null

			fi
		fi
		
		if [ "$var" = "node_add" ] ; then
			bspc node -f $id
		else
			bspc node -f biggest.local	
		fi
	done;
