#!/bin/sh

#
# Functions
#



#
# Main Program
#

cmd=$1; shift

case $cmd in
	toggle_auto)
		if pkill auto_balance ; then
			polybar-msg hook bspwm_mode 1 &>/dev/null
		else
			rund $BSPWM_BIN/mode/balance/balance_all
			polybar-msg hook bspwm_mode 2 &>/dev/null
			rund $BSPWM_BIN/mode/balance/auto_balance
		fi

		;;

	balance)
		rund $BSPWM_BIN/mode/balance/balance_all
		;;

	*)
		polybar-msg hook bspwm_mode 3 &>/dev/null
	esac

