#!/usr/bin/env bash

# global vars passed to the script as arguments
CURRENT_SESSION_ID="$1"

if [ `tmux list-sessions | wc -l` -gt 1 ] ; then
  tmux choose-tree -w -O time -f "#{!=:#{session_id},$CURRENT_SESSION_ID}" "move-window -s '%%'"
else
  tmux display-message "No other session"
fi
